#!/usr/bin/python
import subprocess
def audio(device,col):
    cmd=f"amixer sget {device} | awk 'END{{print ${col}}}' | tr -d []"
    #out = subprocess.run(cmd,capture_output=True,shell=True)
    out = subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)
    return out.stdout.readline().decode().strip()
speaker_stat=audio("Master",6)
speaker_vol=int(audio("Master",5).strip(' \t\n\r%'))
mic_stat=audio("Capture",5)
mic_vol=int(audio("Capture",4).strip(' \t\n\r%'))
if speaker_vol<1 or speaker_stat == "off":
    print(" ",end=" ")
elif speaker_vol <35:
    print(f" {speaker_vol}%",end=" ")
elif speaker_vol < 70:
    print(f" {speaker_vol}%",end=" ")
else:
    print(f"  {speaker_vol}%",end=" ")

if mic_vol<1 or mic_stat == "off":
    print("",end="")
elif mic_vol>0:
    print(f" {mic_vol}%",end="")
